spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mazx2369@gmail.com
spring.mail.password=iafliiivbpgwhmac
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.boot.context.config=DEBUG
logging.file.name=logs/application.log
logging.file.path=logs  
logging.level.root=DEBUG
server.port=8087